version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cli-table
    versions:
    - 0.3.4
    - 0.3.5
  - dependency-name: ora
    versions:
    - 5.3.0
  - dependency-name: chalk
    versions:
    - 4.1.0
